name: backend
services:
  php-dev:
    build:
      context: ..
      dockerfile: docker/php-dev.Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /mnt/programing/php
      - type: volume
        source: php-vscode-server
        target: /root/.vscode-server
    env_file:
      - ../.env
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
    # tty: true
    # stdin_open: true
  php-server:
    build:
      context: ..
      dockerfile: docker/php-server.Dockerfile
    develop:
      watch:
        - path: ..
          action: sync
          # ignore: "*.env"
          target: /app
    ports:
      - 127.0.0.1:8080:80
    env_file:
      - ../.env
    depends_on:
      - db
  db:
    image: postgres:17
    env_file:
      - db.env
    volumes:
      - type: volume
        source: ipz-postgres-data
        target: /var/lib/postgresql/data
      # Опціонально: директорія з ініціалізаційними скриптами
      # - type: bind
      #   source: /docker/initdb.sql
      #   target: /docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5432:5432 
volumes:
  php-vscode-server:
    name: php-vscode-server
  ipz-postgres-data:
    name: ipz-postgres-data