name: backend
services:
  php-dev:
    build:
      context: ..
      dockerfile: docker/php-dev.Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /mnt/programing/php
      - type: volume
        source: php-vscode-server
        target: /root/.vscode-server
    working_dir: /mnt/programing/php
    command: php -S 0.0.0.0:80 -t /mnt/programing/php/public
    environment:
      - WORKING_DIR=/mnt/programing/php
      - PHPRC=/mnt/programing/php/php.ini
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
    # tty: true
    # stdin_open: true
  php-server:
    build:
      context: ..
      dockerfile: docker/php-server.Dockerfile
    develop:
      watch:
        - path: ..
          action: rebuild
    ports:
      - 127.0.0.1:8080:80
    # env_file:
    #   - .php-server
    depends_on:
      - db
  db:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    env_file:
      - .mongo
    volumes:
      - type: volume
        source: ipz-mongodb-data
        target: /data/db
      # Опціонально: директорія з ініціалізаційними скриптами
      - type: bind
        source: D:/Workspace/Programing/mongodb/ipz/scripts
        target: /docker-entrypoint-initdb.d
    working_dir: /mnt/mongodb
volumes:
  php-vscode-server:
    name: php-vscode-server
  ipz-mongodb-data:
    name: ipz-mongodb-data
